#!/usr/bin/env python

import os
import sys
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_NAME, MODEL_CACHE, TOKENIZER_MODEL_NAME, TOKEN_CACHE

tokenizer = AutoTokenizer.from_pretrained(
    TOKENIZER_MODEL_NAME,
    cache_dir=TOKEN_CACHE
)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16,
)